/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Dao.UnidadeSaudeDao;
import classJava.UnidadeSaude;
import javax.swing.JOptionPane;

/**
 *
 * @author Caio
 */
public class CadastroUnid extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLab
     */
    public CadastroUnid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldMunicipio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUnidadeSaude = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldnProtocolo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUF = new javax.swing.JTextField();
        jTextFieldCNESUS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldProntuario = new javax.swing.JFormattedTextField();
        Cadastrar = new javax.swing.JLabel();
        Limpar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CNES da Unidade de Saúde");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));
        getContentPane().add(jTextFieldMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 288, 180, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Unidade de Saúde");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 145, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("N° Protocolo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jTextFieldUnidadeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUnidadeSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUnidadeSaude, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 166, 264, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Município");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));
        getContentPane().add(jTextFieldnProtocolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 227, 264, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("UF");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 267, -1, -1));
        getContentPane().add(jTextFieldUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 288, 65, 29));

        jTextFieldCNESUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCNESUSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCNESUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 110, 264, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Prontuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));
        getContentPane().add(jTextFieldProntuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 100, 30));

        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/cadastrarcamp.png"))); // NOI18N
        Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/limparcamp.png"))); // NOI18N
        Limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimparMouseClicked(evt);
            }
        });
        getContentPane().add(Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/pesquisarcamp.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/voltarpng.png"))); // NOI18N
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundos/fundouni2.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUnidadeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUnidadeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUnidadeSaudeActionPerformed

    private void jTextFieldCNESUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCNESUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCNESUSActionPerformed

    private void CadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMouseClicked
        // TODO add your handling code here:
        if(jTextFieldCNESUS.getText().equals("") || jTextFieldMunicipio.getText().equals("") || jTextFieldProntuario.equals("")
          || jTextFieldUF.getText().equals("") || jTextFieldUnidadeSaude.getText().equals("") || jTextFieldnProtocolo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campos Obrigatorios Deixados em Branco!");
        }else{
            UnidadeSaude uni=new UnidadeSaude();
            uni.setCNESUS(jTextFieldCNESUS.getText());
            uni.setMunicipio(jTextFieldMunicipio.getText());
            uni.setNProtocolo(jTextFieldnProtocolo.getText());
            uni.setProntuario(jTextFieldProntuario.getText());
            uni.setUF(jTextFieldUF.getText());
            uni.setUnidadeSaude(jTextFieldUnidadeSaude.getText());
            UnidadeSaudeDao dao= new UnidadeSaudeDao();
            uni=dao.salvar(uni);
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            jTextFieldCNESUS.setText("");
            jTextFieldMunicipio.setText("");
            jTextFieldProntuario.setText("");
            jTextFieldUF.setText("");
            jTextFieldUnidadeSaude.setText("");
            jTextFieldnProtocolo.setText("");
        
        }
    }//GEN-LAST:event_CadastrarMouseClicked

    private void LimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimparMouseClicked
        // TODO add your handling code here:
        jTextFieldCNESUS.setText("");
            jTextFieldMunicipio.setText("");
            jTextFieldProntuario.setText("");
            jTextFieldUF.setText("");
            jTextFieldUnidadeSaude.setText("");
            jTextFieldnProtocolo.setText("");
    }//GEN-LAST:event_LimparMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUnid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUnid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUnid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUnid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUnid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cadastrar;
    private javax.swing.JLabel Limpar;
    private javax.swing.JLabel Voltar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldCNESUS;
    private javax.swing.JTextField jTextFieldMunicipio;
    private javax.swing.JFormattedTextField jTextFieldProntuario;
    private javax.swing.JTextField jTextFieldUF;
    private javax.swing.JTextField jTextFieldUnidadeSaude;
    private javax.swing.JTextField jTextFieldnProtocolo;
    // End of variables declaration//GEN-END:variables
}
