/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;
import  classJava.Laboratorio;
import Dao.LaboratorioDao;
import formatador.classes.Formatador;
/**
 *
 * @author Caio
 */
public class CadastroLab extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLab
     */
    public CadastroLab() {
        initComponents();
        Recebido=new Formatador(jTextFieldRecebido, "##/##/####");
    }
    private final Formatador Recebido;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMunicipio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeLaboratorio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumeroLaboratorio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUF = new javax.swing.JTextField();
        jTextFieldCNESLaboratorio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JLabel();
        Limpar = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JLabel();
        jTextFieldRecebido = new javax.swing.JTextField();
        Voltar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/buttonlab1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CNES do Laboratório");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 88, -1, -1));
        getContentPane().add(jTextFieldMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 288, 180, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome do Laboratório");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 145, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Numero do Laboratório");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 206, -1, -1));

        jTextFieldNomeLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeLaboratorioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 166, 264, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Município");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));
        getContentPane().add(jTextFieldNumeroLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 227, 264, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("UF");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 267, -1, -1));
        getContentPane().add(jTextFieldUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 288, 65, 29));

        jTextFieldCNESLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCNESLaboratorioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCNESLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 110, 264, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Recebido em:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/cadastrarcamp.png"))); // NOI18N
        Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/limparcamp.png"))); // NOI18N
        Limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimparMouseClicked(evt);
            }
        });
        getContentPane().add(Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/pesquisarcamp.png"))); // NOI18N
        getContentPane().add(Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));
        getContentPane().add(jTextFieldRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 110, 30));

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/voltarpng.png"))); // NOI18N
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundos/fundouni2.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeLaboratorioActionPerformed

    private void jTextFieldCNESLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCNESLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCNESLaboratorioActionPerformed

    private void CadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMouseClicked
        // TODO add your handling code here:
        if(jTextFieldCNESLaboratorio.equals("") || jTextFieldMunicipio.equals("") || jTextFieldNomeLaboratorio.equals("")
          || jTextFieldNumeroLaboratorio.equals("") || jTextFieldRecebido.equals("") || jTextFieldUF.equals("")){
            JOptionPane.showMessageDialog(this, "Há Campos Deixados em Branco");
        }else{
            Laboratorio la= new Laboratorio();
            la.setCNESLaboratorio(jTextFieldCNESLaboratorio.getText());
            la.setMunicipio(jTextFieldMunicipio.getText());
            la.setNomeLaboratorio(jTextFieldNomeLaboratorio.getText());
            la.setNumeroLaboratorio(Integer.parseInt(jTextFieldNumeroLaboratorio.getText()));
            la.setRecebido(jTextFieldRecebido.getText());
            la.setUF(jTextFieldUF.getText());
            LaboratorioDao Dao=new LaboratorioDao();
            la= Dao.salvar(la);
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            dispose();
            CadastroLab lab = new CadastroLab();
            lab.setVisible(true);
        }
    }//GEN-LAST:event_CadastrarMouseClicked

    private void LimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimparMouseClicked
        // TODO add your handling code here:
        jTextFieldCNESLaboratorio.setText("");
        jTextFieldMunicipio.setText("");
        jTextFieldNomeLaboratorio.setText("");
        jTextFieldNumeroLaboratorio.setText("");
        jTextFieldRecebido.setText("");
        jTextFieldUF.setText("");
    }//GEN-LAST:event_LimparMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cadastrar;
    private javax.swing.JLabel Limpar;
    private javax.swing.JLabel Pesquisar;
    private javax.swing.JLabel Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldCNESLaboratorio;
    private javax.swing.JTextField jTextFieldMunicipio;
    private javax.swing.JTextField jTextFieldNomeLaboratorio;
    private javax.swing.JTextField jTextFieldNumeroLaboratorio;
    private javax.swing.JTextField jTextFieldRecebido;
    private javax.swing.JTextField jTextFieldUF;
    // End of variables declaration//GEN-END:variables
}
