/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Dao.UsuarioDao;
import classJava.Usuario;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Caio
 */
public class PesquisarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PesquisarUsuario
     */
    public PesquisarUsuario() {
        initComponents();
        setIcon();
        preenchendoTable();
    }
public void preenchendoTable(){
         UsuarioDao dao=new UsuarioDao();
            List<Usuario> usuario=dao.conAutenticar();
          DefaultTableModel dtmUsuario = (DefaultTableModel) jTableUsuario.getModel();
             if(usuario !=null){
            for(Usuario u: usuario){
            Object[] dados={u.getId(), u.getNome(), u.getEmail(), u.getLogin(), u.getSenha(), u.getNivelDeAcesso()};
            dtmUsuario.addRow(dados);
            
            }}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldFlitra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        novo2 = new javax.swing.JLabel();
        Editar2 = new javax.swing.JLabel();
        Excluir2 = new javax.swing.JLabel();
        voltar2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Edi1 = new javax.swing.JLabel();
        novo1 = new javax.swing.JLabel();
        Excluir1 = new javax.swing.JLabel();
        voltar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisar Usuário");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pesquisar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 20));

        jTextFieldFlitra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFlitraKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldFlitra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 270, -1));

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "E-mail", "Login", "Senha", "Nivel de Usuariol"
            }
        ));
        jScrollPane1.setViewportView(jTableUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 620, 214));

        novo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PesquisarIMG/novo32d.png"))); // NOI18N
        novo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novo2MouseClicked(evt);
            }
        });
        getContentPane().add(novo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        Editar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PesquisarIMG/editar34f.png"))); // NOI18N
        Editar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Editar2MouseClicked(evt);
            }
        });
        getContentPane().add(Editar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        Excluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PesquisarIMG/excluirpng23.png"))); // NOI18N
        Excluir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Excluir2MouseClicked(evt);
            }
        });
        getContentPane().add(Excluir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        voltar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PesquisarIMG/voltaricon.png"))); // NOI18N
        voltar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltar2MouseClicked(evt);
            }
        });
        getContentPane().add(voltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PesquisarIMG/pesquisaodsakda13232.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 40));

        Edi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/buttonedit45.png"))); // NOI18N
        Edi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edi1MouseClicked(evt);
            }
        });
        getContentPane().add(Edi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 50, 60));

        novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/novopng.png"))); // NOI18N
        novo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novo1MouseClicked(evt);
            }
        });
        getContentPane().add(novo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 40));

        Excluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/excluir1png.png"))); // NOI18N
        Excluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Excluir1MouseClicked(evt);
            }
        });
        getContentPane().add(Excluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 40, 50));

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PesquisarIMG/voltarpng.png"))); // NOI18N
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PesquisarIMG/fundolegal.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Excluir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Excluir2MouseClicked
                  if(jTableUsuario.getSelectedRow() != 1){
                    DefaultTableModel dtmUsuario = (DefaultTableModel) jTableUsuario.getModel();
                    int id=(int) (jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 0));
                    Usuario u=new Usuario();
                    UsuarioDao dao=new UsuarioDao();
                    System.out.println(id);
                    dao.remover(Usuario.class, id);
                      System.out.println(u);
                    dtmUsuario.removeRow(jTableUsuario.getSelectedRow());
                  }else{
                      JOptionPane.showMessageDialog(null,"seleciona uma linha da tabela.");
                  }
    }//GEN-LAST:event_Excluir2MouseClicked

    private void Excluir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Excluir1MouseClicked
        // TODO add your handling code here:
         if(jTableUsuario.getSelectedRow() != 1){
                    DefaultTableModel dtmUsuario = (DefaultTableModel) jTableUsuario.getModel();
                    int id=(int) (jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 0));
                    Usuario u=new Usuario();
                    UsuarioDao dao=new UsuarioDao();
                    
                    dao.remover(Usuario.class, id);
                    dtmUsuario.removeRow(jTableUsuario.getSelectedRow());
                  }
    }//GEN-LAST:event_Excluir1MouseClicked

    private void novo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novo2MouseClicked
        dispose();
        CadastroUsuario1 prin=new CadastroUsuario1();
        prin.setVisible(true);
    }//GEN-LAST:event_novo2MouseClicked

    private void novo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novo1MouseClicked
        // TODO add your handling code here:
        dispose();
        CadastroUsuario1 prin=new CadastroUsuario1();
        prin.setVisible(true);
    }//GEN-LAST:event_novo1MouseClicked

    private void Editar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar2MouseClicked
        if(jTableUsuario.getSelectedRow() != -1){
             dispose();
                    DefaultTableModel dtmUsuario = (DefaultTableModel) jTableUsuario.getModel();
                    int id=(int) (jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 0));
                    UsuarioDao dao=new UsuarioDao();
                    Usuario usu=new Usuario();
                    usu.setId(id);
                    UPUsuario1 prin=new UPUsuario1();
                    prin.exporta(usu);
                    prin.setVisible(true);
        }else{
        JOptionPane.showMessageDialog(this, "selecione uma linha da tabela");
        
        }
    }//GEN-LAST:event_Editar2MouseClicked
TableRowSorter trs ;
    private void jTextFieldFlitraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFlitraKeyTyped
        DefaultTableModel dtmUsuario = (DefaultTableModel) jTableUsuario.getModel();
        
        jTextFieldFlitra.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent ke) {
            trs.setRowFilter(RowFilter.regexFilter(jTextFieldFlitra.getText(), 1));
            }
});
        trs=new TableRowSorter(dtmUsuario);
        jTableUsuario.setRowSorter(trs);
    }//GEN-LAST:event_jTextFieldFlitraKeyTyped

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        // TODO add your handling code here:
        dispose();
        PrincipalADM prin = new PrincipalADM();
        prin.setVisible(true);
    }//GEN-LAST:event_voltarMouseClicked

    private void voltar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltar2MouseClicked
        // TODO add your handling code here:
        dispose();
        PrincipalADM prin = new PrincipalADM();
        prin.setVisible(true);
    }//GEN-LAST:event_voltar2MouseClicked

    private void Edi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edi1MouseClicked

      if(jTableUsuario.getSelectedRow() != -1){
             dispose();
                    DefaultTableModel dtmUsuario = (DefaultTableModel) jTableUsuario.getModel();
                    int id=(int) (jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 0));
                    UsuarioDao dao=new UsuarioDao();
                    Usuario usu=new Usuario();
                    usu.setId(id);
                    UPUsuario1 prin=new UPUsuario1();
                    prin.exporta(usu);
                    prin.setVisible(true);
        }else{
        JOptionPane.showMessageDialog(this, "selecione uma linha da tabela");
        
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Edi1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              try {
            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaWhiteVisionLookAndFeel");
        } catch (Exception e) {
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Edi1;
    private javax.swing.JLabel Editar2;
    private javax.swing.JLabel Excluir1;
    private javax.swing.JLabel Excluir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFieldFlitra;
    private javax.swing.JLabel novo1;
    private javax.swing.JLabel novo2;
    private javax.swing.JLabel voltar;
    private javax.swing.JLabel voltar2;
    // End of variables declaration//GEN-END:variables
    //aaaaaa

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconeframe.png")));
    }
}
