/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Dao.UsuarioDao;
import classJava.Usuario;
import java.awt.Toolkit;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Caio
 */
public class UPUsuario1 extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario1
     */
    public UPUsuario1() {
        initComponents();
        setIcon();
       
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        textLoginl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boxNivelUsuario = new javax.swing.JComboBox<String>();
        ButtonSalvar = new javax.swing.JButton();
        passwordSenha = new javax.swing.JPasswordField();
        voltar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, -1, -1));
        getContentPane().add(textLoginl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, 204, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));
        getContentPane().add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, 430, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Login");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, -1, -1));
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, 430, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Senha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 289, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nivel de Usuário");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 363, -1, -1));

        boxNivelUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha o nivel", "Administrador", "Atendente", "Digitador" }));
        boxNivelUsuario.setToolTipText("");
        getContentPane().add(boxNivelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 398, 204, 28));

        ButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NavIMG/salvardos23.png"))); // NOI18N
        ButtonSalvar.setContentAreaFilled(false);
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 130, 50));

        passwordSenha.setText("jPasswordField1");
        getContentPane().add(passwordSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 30));

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/voltarpng.png"))); // NOI18N
        voltar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                voltarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/imagefundomenor.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 466, 530));
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   public void exporta(Usuario usu){
    UsuarioDao dao =new UsuarioDao();
    usu=dao.obter(Usuario.class, usu.getId());
    cod.setText(""+usu.getId());
    textNome.setText(usu.getNome());
    textEmail.setText(usu.getEmail());
    textLoginl.setText(usu.getLogin());
    passwordSenha.setText(usu.getSenha());
    if(usu.getNivelDeAcesso().equals("Administrador")){
        boxNivelUsuario.setSelectedIndex(1);
    }else if(usu.getNivelDeAcesso().equals("Atendente")){
    boxNivelUsuario.setSelectedIndex(2);
    }else{
    boxNivelUsuario.setSelectedIndex(3);
    }
    }
    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
       if(textNome.getText().equals("") || passwordSenha.getText().equals("")|| textEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Campo Obrigatorio Deixado em Branco"); 
                    }
        else if( boxNivelUsuario.getSelectedItem().equals("Escolha o nivel")){
            JOptionPane.showMessageDialog(null,"Você não escolheu o nivel de acesso");
        }
        else{
            Usuario usu=new Usuario();
           int i = Integer.parseInt(cod.getText());
            usu.setId(i);
            usu.setNome(textNome.getText());
            usu.setSenha(passwordSenha.getText());
            usu.setEmail(textEmail.getText());
            usu.setLogin(textLoginl.getText());
            usu.setNivelDeAcesso((String) boxNivelUsuario.getSelectedItem());
            UsuarioDao dao= new UsuarioDao();
            usu= dao.salvar(usu);
            JOptionPane.showMessageDialog(null, "Usuario editado com sucesso");
            dispose();
            PesquisarUsuario Prin = new PesquisarUsuario();
            Prin.setVisible(true);
        
        }
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void voltarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_voltarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarAncestorAdded

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
       dispose();
       PrincipalADM Prin = new PrincipalADM();
       Prin.setVisible(true);

    }//GEN-LAST:event_voltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaWhiteVisionLookAndFeel");
        } catch (Exception e) {
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPUsuario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JComboBox<String> boxNivelUsuario;
    private javax.swing.JLabel cod;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField passwordSenha;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textLoginl;
    private javax.swing.JTextField textNome;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconeframe.png")));
    }
}
